#!/bin/bash

set -e

#############################################
################ FEMU CONFIG  ###############
#############################################

zns_size_mb=8192 # Device size in MiB, requires this amount of RAM from host
hw_sector_size=4096 # bytes

##### DEFAULTS NEEDED #####
FEMU_OPTIONS="-device femu"
FEMU_OPTIONS=${FEMU_OPTIONS},devsz_mb=${zns_size_mb}
FEMU_OPTIONS=${FEMU_OPTIONS},femu_mode=3
FEMU_OPTIONS=${FEMU_OPTIONS},id=nvme0
FEMU_OPTIONS=${FEMU_OPTIONS},mdts=10 # in units of memory page size (4KiB) and shown as 2^x (4MiB with 10, also default)
FEMU_OPTIONS=${FEMU_OPTIONS}",lsec_size=${hw_sector_size}"

##### PERFORMANCE CONFIGS #####
num_channels=2
chips_per_channel=2
num_planes_per_chip=2
num_sectors_per_page=4
num_pages_per_block=512

# Flash Latencies in nanoseconds (HARDCODED IN SOURCE CODE)
# NAND_READ_LATENCY = 40000
# NAND_PROG_LATENCY = 200000
# NAND_ERASE_LATENCY = 2000000

FEMU_OPTIONS=${FEMU_OPTIONS},lnum_ch=${num_channels}
FEMU_OPTIONS=${FEMU_OPTIONS},lnum_lun=${chips_per_channel}
FEMU_OPTIONS=${FEMU_OPTIONS}",lnum_pln=${num_planes_per_chip}"
FEMU_OPTIONS=${FEMU_OPTIONS}",lsecs_per_pg=${num_sectors_per_page}"
FEMU_OPTIONS=${FEMU_OPTIONS}",lpgs_per_blk=${num_pages_per_block}"
#FEMU_OPTIONS=${FEMU_OPTIONS}",flash_type=3" # 3 for TLC, 4 for QLC, 2 (default) for MLC

#############################################
############## END FEMU CONFIG  #############
#############################################

U20_IMG="/home/nty/src/images/ubuntu-22.04-f2fs.qcow2"
# U20_IMG="/home/nty/src/images/ubuntu-22.04.qcow2"

sudo ${FEMU_BUILD}/qemu-system-x86_64 -name f2fs-vm -m 20G -cpu host -smp 16 -enable-kvm -nographic \
    -hda ${U20_IMG} \
    -device virtio-scsi-pci,id=scsi0 \
    ${FEMU_OPTIONS} \
    -device vfio-pci,host=0000:60:00.0 \
    -device vfio-pci,host=0000:88:00.0 \
    -net nic,model=virtio \
    -net user,hostfwd=tcp::8888-:22,hostfwd=tcp::3333-:3000 \
    -device virtio-tablet-pci,id=tablet0,serial=virtio-tablet \
