#!/bin/bash

set -e

#############################################
############### Setup Devices ###############
#### With Krien/ZNS_personal_Qemu_config ####
#############################################

DEVICE_PATH="devices/"

# used for debugging non-zns 
smallnvme="${DEVICE_PATH}nvmessd-32M.img"
nvme_blocksize=512
# used for hybrid approaches (e.g. F2FS)
bignvme="${DEVICE_PATH}nvmessd-4G.img"
# small IO (should be similar sized disks for benchmarking)
smallzns="${DEVICE_PATH}znsssd-128M.img"
smallzns2="${DEVICE_PATH}znsssd2-128M.img"
smallzns_logical_blocksize=512
smallzns_physical_blocksize=512
# NOTE: Zone size and capacity have to be a power of 2 value 
smallzns_zonesize=2M
smallzns_zonecap=1M
smallzns_max_open=16
smallzns_max_active=32
smallzns_mdts=8
smallzns_zasl=5
smallzns_max_ioqpairs=64
# Medium sized ZNS for F2FS GC-calls benchmark
mediumzns="${DEVICE_PATH}znsssd-4G.img"
mediumzns_logical_blocksize=512
mediumzns_physical_blocksize=512
mediumzns_zonesize=128M
mediumzns_zonecap=64M
mediumzns_max_open=16
mediumzns_max_active=32
mediumzns_mdts=8
mediumzns_zasl=5
mediumzns_max_ioqpairs=64
# bigger IO (should be similar sized disks for benchmarking)
biggerzns="${DEVICE_PATH}znsssd3-8G.img"
biggerzns2="${DEVICE_PATH}znsssd4-8G.img"
biggerzns_logical_blocksize=512
biggerzns_physical_blocksize=512
biggerzns_zonesize=2M
biggerzns_zonecap=1M
biggerzns_max_open=16
biggerzns_max_active=32
biggerzns_mdts=8
biggerzns_zasl=5
biggerzns_max_ioqpairs=64
# different ZNS configurations (different zonesize, lbasize etc...)
altzns="${DEVICE_PATH}znsssd5-1G.img"
altzns2="${DEVICE_PATH}znsssd6-1G.img"
altzns_logical_blocksize=512
altzns_physical_blocksize=512
altzns_zonesize=4M
altzns_zonecap=2M
altzns_max_open=16
altzns_max_active=32
altzns_mdts=9
altzns_zasl=0
altzns_max_ioqpairs=32
# taken from https://zonedstorage.io/docs/tools/qemu, better not alter...
zns_uuid=5e40ec5f-eeb6-4317-bc5e-c919796a5f79

# I thought we were going to write Bash?
# This was mainly done to reduce column width as Qemu's opts are "," separated, so "\" will not work.
# If we want we can make this shorter with double evaluation, but not sure if this destroys readability.
nvme_opts="physical_block_size=$nvme_blocksize,logical_block_size=$nvme_blocksize"

zns_opts="uuid=${zns_uuid},zoned=true"

small_ctrl_opts="mdts=${smallzns_mdts},zoned.zasl=${smallzns_zasl},max_ioqpairs=${smallzns_max_ioqpairs}"
small_opts="logical_block_size=${smallzns_logical_blocksize},physical_block_size=${smallzns_physical_blocksize}"
small_opts="${small_opts},zoned.zone_size=${smallzns_zonesize},zoned.zone_capacity=${smallzns_zonecap}"
small_opts="${small_opts},zoned.max_open=${smallzns_max_open},zoned.max_active=${smallzns_max_active}"

medium_ctrl_opts="mdts=${mediumzns_mdts},zoned.zasl=${mediumzns_zasl},max_ioqpairs=${mediumzns_max_ioqpairs}"
medium_opts="logical_block_size=${mediumzns_logical_blocksize},physical_block_size=${mediumzns_physical_blocksize}"
medium_opts="${medium_opts},zoned.zone_size=${mediumzns_zonesize},zoned.zone_capacity=${mediumzns_zonecap}"
medium_opts="${medium_opts},zoned.max_open=${mediumzns_max_open},zoned.max_active=${mediumzns_max_active}"

bigger_ctrl_opts="mdts=${biggerzns_mdts},zoned.zasl=${biggerzns_zasl},max_ioqpairs=${biggerzns_max_ioqpairs}"
bigger_opts="logical_block_size=${biggerzns_logical_blocksize},physical_block_size=${biggerzns_physical_blocksize}"
bigger_opts="${bigger_opts},zoned.zone_size=${biggerzns_zonesize},zoned.zone_capacity=${biggerzns_zonecap}"
bigger_opts="${bigger_opts},zoned.max_open=${biggerzns_max_open},zoned.max_active=${biggerzns_max_active}"

alt_ctrl_opts="mdts=${altzns_mdts},zoned.zasl=${altzns_zasl},max_ioqpairs=${altzns_max_ioqpairs}"
alt_opts="logical_block_size=${altzns_logical_blocksize},physical_block_size=${altzns_physical_blocksize}"
alt_opts="${alt_opts},zoned.zone_size=${altzns_zonesize},zoned.zone_capacity=${altzns_zonecap}"
alt_opts="${alt_opts},zoned.max_open=${altzns_max_open},zoned.max_active=${altzns_max_active}"

#############################################
################# Start qemu ################
#############################################
# -S: Do not start CPU at startup (you must type 'c' in the monitor). From gdb
# -s: Shorthand for -gdb tcp::1234, i.e. open a gdbserver on TCP port 1234

U20_IMG="${HOME}/src/storage/images/ubuntu-20.04.qcow2"

sudo $QEMU_HOME/build/qemu-system-x86_64 -name f2fs-vm -m 4G -cpu host -smp 4 -enable-kvm -nographic \
    -hda $U20_IMG \
    -kernel $HOME/src/storage/f2fs/arch/x86/boot/bzImage \
    -append "root=/dev/sdb2 rootfstype=ext4 console=ttyS0" \
    -net nic,model=virtio -net user,hostfwd=tcp::8888-:22,hostfwd=tcp::3333-:3000 -device virtio-tablet-pci,id=tablet0,serial=virtio-tablet \
    -drive file="$smallnvme",id=nvme-device,format=raw,if=none    \
    -device "nvme,drive=nvme-device,serial=nvme-dev,${nvme_opts}" \
    -drive file="$bignvme",id=nvme-device2,format=raw,if=none       \
    -device "nvme,drive=nvme-device2,serial=nvme-dev2,${nvme_opts}" \
    -drive file="$smallzns",id=zns-device1,format=raw,if=none     \
    -drive file="$smallzns2",id=zns-device2,format=raw,if=none    \
    -drive file="$biggerzns",id=zns-device3,format=raw,if=none    \
    -drive file="$biggerzns2",id=zns-device4,format=raw,if=none   \
    -drive file="$altzns",id=zns-device5,format=raw,if=none       \
    -drive file="$altzns2",id=zns-device6,format=raw,if=none      \
    -drive file="$mediumzns",id=zns-device7,format=raw,if=none    \
    -device "nvme,serial=zns-dev1,id=nvme2,${small_ctrl_opts}"  \
    -device "nvme,serial=zns-dev2,id=nvme3,${small_ctrl_opts}"  \
    -device "nvme,serial=zns-dev3,id=nvme4,${bigger_ctrl_opts}" \
    -device "nvme,serial=zns-dev4,id=nvme5,${bigger_ctrl_opts}" \
    -device "nvme,serial=zns-dev5,id=nvme6,${alt_ctrl_opts}"    \
    -device "nvme,serial=zns-dev6,id=nvme7,${alt_ctrl_opts}"    \
    -device "nvme,serial=zns-dev7,id=nvme8,${medium_ctrl_opts}" \
    -device "nvme-ns,drive=zns-device1,bus=nvme2,nsid=1,${zns_opts},${small_opts}"  \
    -device "nvme-ns,drive=zns-device2,bus=nvme3,nsid=1,${zns_opts},${small_opts}"  \
    -device "nvme-ns,drive=zns-device3,bus=nvme4,nsid=1,${zns_opts},${bigger_opts}" \
    -device "nvme-ns,drive=zns-device4,bus=nvme5,nsid=1,${zns_opts},${bigger_opts}" \
    -device "nvme-ns,drive=zns-device5,bus=nvme6,nsid=1,${zns_opts},${alt_opts}"    \
    -device "nvme-ns,drive=zns-device6,bus=nvme7,nsid=1,${zns_opts},${alt_opts}"    \
    -device "nvme-ns,drive=zns-device7,bus=nvme8,nsid=1,${zns_opts},${medium_opts}" \
    -S -s \
